Repository tjroeder/little-esty-shop, pull requests merged in 2022-01, with the labels that each got.

#41 Resolves #41
  Gemfile
  Gemfile.lock
  spec/rails_helper.rb
  spec/support/factory_bot.rb
Labels: enhancement

#45 Resolves #40
  Gemfile.lock
  app/controllers/merchants_controller.rb
  app/views/merchants/dashboard.html.erb
  app/views/merchants/show.html.erb
  config/routes.rb
  spec/features/customers/edit.html.erb_spec.rb
  spec/features/customers/index.html.erb_spec.rb
  spec/features/customers/new.html.erb_spec.rb
  spec/features/customers/show.html.erb_spec.rb
  spec/features/invoices/edit.html.erb_spec.rb
  spec/features/invoices/index.html.erb_spec.rb
  spec/features/invoices/new.html.erb_spec.rb
  spec/features/invoices/show.html.erb_spec.rb
  spec/features/items/edit.html.erb_spec.rb
  spec/features/items/index.html.erb_spec.rb
  spec/features/items/new.html.erb_spec.rb
  spec/features/items/show.html.erb_spec.rb
  spec/features/merchants/dashboard_spec.rb
  spec/features/merchants/edit.html.erb_spec.rb
  spec/features/merchants/index.html.erb_spec.rb
  spec/features/merchants/new.html.erb_spec.rb
  spec/features/transactions/edit.html.erb_spec.rb
  spec/features/transactions/index.html.erb_spec.rb
  spec/features/transactions/new.html.erb_spec.rb
  spec/features/transactions/show.html.erb_spec.rb
  spec/models/merchant_spec.rb
  spec/views/merchants/show.html.erb_spec.rb
Labels: enhancement

#47 Created relationships and tests
  app/models/customer.rb
  app/models/invoice.rb
  app/models/item.rb
  app/models/merchant.rb
  app/models/transaction.rb
  spec/features/invoices/edit.html.erb_spec.rb
  spec/features/invoices/new.html.erb_spec.rb
  spec/features/items/edit.html.erb_spec.rb
  spec/features/items/new.html.erb_spec.rb
  spec/features/transactions/edit.html.erb_spec.rb
  spec/features/transactions/new.html.erb_spec.rb
  spec/models/customer_spec.rb
  spec/models/invoice_spec.rb
  spec/models/item_spec.rb
  spec/models/merchant_spec.rb
  spec/models/transaction_spec.rb
Labels: enhancement

#49 PR: Factory bot setup
  app/controllers/invoices_controller.rb
  app/views/invoices/index.html.erb
  config/routes.rb
  spec/factories/customers.rb
  spec/factories/invoice_items.rb
  spec/factories/invoices.rb
  spec/factories/items.rb
  spec/factories/merchants.rb
  spec/factories/transactions.rb
  spec/features/invoices/index.html.erb_spec.rb
  spec/models/invoice_spec.rb
  spec/models/transaction_spec.rb
Labels: enhancement

#50 Resolved #38
  Gemfile
  Gemfile.lock
  app/models/merchant.rb
  app/views/dashboards/index.html.erb
  spec/features/dashboards/index_spec.rb
  spec/models/merchant_spec.rb
Labels: Advanced AR

#52 Merch dash items ready ship part1
  app/models/merchant.rb
  app/views/dashboards/index.html.erb
  spec/features/dashboards/index_spec.rb
  spec/models/merchant_spec.rb
Labels: ActiveRecord

#51 Resolves #27
  app/controllers/invoices_controller.rb
  app/views/invoices/index.html.erb
  app/views/invoices/show.html.erb
  config/routes.rb
  spec/features/invoices/index.html.erb_spec.rb
  spec/models/invoice_spec.rb
Labels: enhancement

#54 Merch dash items part 2
  app/models/merchant.rb
  app/views/dashboards/index.html.erb
  spec/features/dashboards/index_spec.rb
  spec/features/invoices/edit.html.erb_spec.rb
  spec/features/invoices/new.html.erb_spec.rb
  spec/features/items/edit.html.erb_spec.rb
  spec/features/items/new.html.erb_spec.rb
  spec/features/transactions/edit.html.erb_spec.rb
  spec/features/transactions/new.html.erb_spec.rb
  spec/models/merchant_spec.rb
Labels: ActiveRecord

#56 Resolves #37
  app/views/dashboards/index.html.erb
  spec/features/dashboards/index_spec.rb
Labels: ActiveRecord

#60 Resolves #23
  app/controllers/invoice_items_controller.rb
  app/helpers/application_helper.rb
  app/models/invoice.rb
  app/models/invoice_item.rb
  app/views/invoices/show.html.erb
  config/routes.rb
  spec/features/invoices/show.html.erb_spec.rb
  spec/helpers/application_helper_spec.rb
  spec/models/invoice_spec.rb
Labels: enhancement

#61 Merch dash items
  app/models/invoice.rb
  app/models/merchant.rb
  app/views/dashboards/index.html.erb
  spec/features/dashboards/index_spec.rb
  spec/features/items/new.html.erb_spec.rb
  spec/features/merchants/dashboard_spec.rb
  spec/models/invoice_spec.rb
  spec/models/merchant_spec.rb
Labels: ActiveRecord

#62 Resolves #22, Resolves #21
  app/controllers/admin/admin_invoices_controller.rb
  app/controllers/admin/admin_merchants_controller.rb
  app/controllers/admin_controller.rb
  app/controllers/invoice_items_controller.rb
  app/models/merchant.rb
  app/views/admin/index.html.erb
  config/routes.rb
  spec/features/admin/index.html.erb_spec.rb
  spec/features/invoices/show.html.erb_spec.rb
  spec/models/merchant_spec.rb
Labels: enhancement

#63 Dashboard Resource
  app/controllers/dashboard_controller.rb
  app/views/dashboard/index.html.erb
  config/routes.rb
  spec/features/dashboards/index_spec.rb
  spec/features/invoices/show.html.erb_spec.rb
  spec/features/merchants/dashboard_spec.rb
Labels: enhancement

#66 Redo 3
  app/controllers/items_controller.rb
  app/models/merchant.rb
  app/views/items/edit.html.erb
  app/views/items/index.html.erb
  app/views/items/show.html.erb
  config/routes.rb
  spec/features/dashboards/index_spec.rb
  spec/features/items/edit.html.erb_spec.rb
  spec/features/items/index.html.erb_spec.rb
  spec/features/items/new.html.erb_spec.rb
  spec/models/item_spec.rb
  spec/models/merchant_spec.rb
Labels: enhancement

#67 update merch model to include correct item ready ship method
  app/models/merchant.rb
  spec/models/merchant_spec.rb
Labels: bug

#68 Resolves #15
  app/controllers/admin/merchants_controller.rb
  app/views/admin/merchants/edit.html.erb
  app/views/admin/merchants/show.html.erb
  config/routes.rb
  spec/features/admin/merchants/edit.html.erb_spec.rb
  spec/features/admin/merchants/show.html.erb_spec.rb
Labels: enhancement

#69 Resolves #20
  app/controllers/admin_controller.rb
  app/models/customer.rb
  app/models/invoice.rb
  app/models/transaction.rb
  app/views/admin/index.html.erb
  spec/factories/customers.rb
  spec/factories/invoice_items.rb
  spec/factories/invoices.rb
  spec/factories/items.rb
  spec/factories/transactions.rb
  spec/features/admin/index.html.erb_spec.rb
  spec/models/customer_spec.rb
  spec/models/invoice_spec.rb
  spec/models/merchant_spec.rb
Labels: enhancement

#70 Resolves #19
  app/controllers/admin/invoices_controller.rb
  app/controllers/admin_controller.rb
  app/models/invoice.rb
  app/views/admin/index.html.erb
  app/views/admin/invoices/show.html.erb
  config/routes.rb
  spec/features/admin/index.html.erb_spec.rb
  spec/models/invoice_spec.rb
Labels: enhancement

#71 Resolves #18
  app/models/invoice.rb
  app/views/admin/index.html.erb
  spec/features/admin/index.html.erb_spec.rb
  spec/models/invoice_spec.rb
Labels: enhancement

#72 Resolves #14, Resolves #13, Resolves #12
  app/controllers/admin/merchants_controller.rb
  app/controllers/merchants_controller.rb
  app/models/merchant.rb
  app/views/admin/merchants/index.html.erb
  app/views/admin/merchants/new.html.erb
  config/routes.rb
  db/migrate/20220109233500_add_status_to_merchants.rb
  db/schema.rb
  spec/features/admin/merchants/index.html.erb_spec.rb
  spec/features/admin/merchants/new.html.erb_spec.rb
  spec/features/admin/merchants/show.html.erb_spec.rb
Labels: enhancement

#75 Resolves $6, #8 and #9
  app/views/admin/invoices/index.html.erb
  app/views/admin/invoices/show.html.erb
  spec/features/admin/invoices/index.html.erb_spec.rb
  spec/features/admin/invoices/show.html.erb_spec.rb
Labels: ActiveRecord

#78 Resolves #7
  app/controllers/admin/invoices_controller.rb
  app/models/customer.rb
  app/models/invoice.rb
  app/models/invoice_item.rb
  app/models/item.rb
  app/views/admin/invoices/index.html.erb
  app/views/admin/invoices/show.html.erb
  config/routes.rb
  spec/features/admin/invoices/show.html.erb_spec.rb
  spec/models/invoice_spec.rb
Labels: enhancement, ActiveRecord

#82 PR: Issue GitHub api
  .gitignore
  Gemfile
  Gemfile.lock
  app/models/invoice.rb
  app/poros/commit.rb
  app/poros/contributor.rb
  app/poros/github_search.rb
  app/poros/github_service.rb
  app/poros/pull_request.rb
  app/poros/repo.rb
  config/routes.rb
  spec/features/admin/index.html.erb_spec.rb
  spec/features/dashboards/index_spec.rb
  spec/fixtures/commits.json
  spec/fixtures/contributors.json
  spec/fixtures/little-esty-shop.json
  spec/fixtures/pulls.json
  spec/fixtures/vcr_cassettes/little_esty_shop_commits.yml
  spec/fixtures/vcr_cassettes/little_esty_shop_pull_requests.yml
  spec/models/customer_spec.rb
  spec/models/invoice_item_spec.rb
  spec/models/invoice_spec.rb
  spec/models/merchant_spec.rb
  spec/poros/commit_spec.rb
  spec/poros/contributor_spec.rb
  spec/poros/github_search_spec.rb
  spec/poros/github_service_spec.rb
  spec/poros/pull_request_spec.rb
  spec/poros/repo_spec.rb
  spec/rails_helper.rb
  spec/spec_helper.rb
Labels: API Consumption

#83 PR: Issue GitHub api
  app/models/invoice.rb
  app/poros/github_search.rb
  app/poros/repo.rb
  spec/fixtures/vcr_cassettes/little_esty_shop_contributors.yml
  spec/fixtures/vcr_cassettes/little_esty_shop_pull_requests.yml
  spec/fixtures/vcr_cassettes/little_esty_shop_repo.yml
  spec/models/invoice_spec.rb
  spec/poros/contributor_spec.rb
  spec/poros/github_search_spec.rb
Labels: enhancement

#84 PR: GitHub service spec tests
  spec/fixtures/vcr_cassettes/little_esty_shop_30_commits.yml
  spec/poros/github_search_spec.rb
  spec/poros/github_service_spec.rb
Labels: enhancement, API Consumption

#85 Test refactor
  .gitignore
  app/controllers/customers_controller.rb
  app/controllers/invoices_controller.rb
  app/controllers/merchants_controller.rb
  app/controllers/transactions_controller.rb
  app/views/admin/merchants/index.html.erb
  config/environments/test.rb
  spec/features/customers/edit.html.erb_spec.rb
  spec/features/customers/index.html.erb_spec.rb
  spec/features/customers/new.html.erb_spec.rb
  spec/features/customers/show.html.erb_spec.rb
  spec/models/merchant_spec.rb
  spec/models/transaction_spec.rb
  spec/rails_helper.rb
  spec/spec_helper.rb
Labels: enhancement

#87 welcome page added
  app/controllers/welcome_controller.rb
  app/views/welcome/index.html.erb
  config/routes.rb
Labels: enhancement

#88 Misc refactors
  app/models/transaction.rb
  app/views/admin/merchants/index.html.erb
  spec/models/transaction_spec.rb
Labels: enhancement

#89 PR: Api last
  app/views/_header.html.erb
  spec/features/_header_spec.rb
  spec/spec_helper.rb
Labels: enhancement
